### ISSUE TITLE
Can I still use CDN in new version

### ISSUE THREAD

**Issue by njzjz** [jiangtj-lab/hexo-next-pwa#23]
Can I still use workbox CDN in new version, or I must use local workbox files?

**Comment by jiangtj** [comment]
Can't, This upgrade uses the internal api of workbox-build, It will package the workbox modules you use to create a local workbox.js

![image](https://user-images.githubusercontent.com/15902347/108612725-2ef01f80-7426-11eb-8703-1bc30222cf70.png)

**Comment by njzjz** [comment]
Thank you!
