### ISSUE TITLE
precached pages cannot be updated after revision

### ISSUE THREAD

**Issue by njzjz** [jiangtj-lab/hexo-next-pwa#31]
Precached pages cannot be updated after revision? I am not sure if it is a bug.

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/137050989-432c2417-1c8d-4d4e-a00a-1deea81c4fb7.png)



It’s best to design a pop-up box to remind users that there are new resources, click for refresh, e.g.  [vite's pwa](https://vite-plugin-pwa.netlify.app/guide/prompt-for-update)

I add skipWaiting as a temporary solution at first  https://github.com/jiangtj-lab/hexo-next-pwa/pull/32

**Comment by jiangtj** [comment]
如果没有调用skipWaiting, 需要关闭浏览器再打开（以前我在脚本里调用了skipWaiting，这次忘记参数里加上了:see_no_evil:）
